### PR TITLE
fix: typo in log-absolute-derivative of exponential transform (normalizing flow tutorial) closes #3176

### LINKED ISSUE #3176: Small typo in tutorial notebook on Normalizing Flows
Hi,

there seems to be a small typo in the [tutorial notebook on normalizing flows](https://github.com/pyro-ppl/pyro/blob/dev/tutorial/source/normalizing_flows_i.ipynb) in section "Fixed Univariate Transforms in Pyro".

The log-absolute derivative of the exponential transform $y = g(x) = \exp(x)$ is stated as $\log(\vert\frac{dg}{dx}\vert)=y$ while it should rather be $\log(\vert\frac{dg}{dx}\vert)=x$ (see also the implementation of [torch.distributions.transforms.ExpTransform](https://pytorch.org/docs/master/_modules/torch/distributions/transforms.html#ExpTransform)).

### PR DESCRIPTION
**Pull request by felixschltr**
This PR addresses Issue #3176

I ran `make test` and `make test-examples` locally just to be sure, but since only a single character inside a notebook markdown cell is changed, there shouldn't be bigger problems.

### CODE REVIEW

**Review by fritzo — APPROVED** [review]
Thanks for the fix!

**Comment by felixschltr** [comment]
Sorry about the failing lint check. Though I'm kind of surprised by this given the small change. Should I request a revert?

**Comment by ordabayevy** [comment]
I think linting is failing because of the new version of the black formatter.

**Comment by martinjankowiak** [comment]
yes let's see if #3178 fixes it

**Pull request merged**
