### PR TITLE
Added type assertion for better code clarity

### PR DESCRIPTION
**Pull request by GautamV234**
I am working with Prof. @nipunbatra and I am currently working on this PR to solve #3026.

### CODE REVIEW

**Comment by fritzo** [comment]
Can you `make lint` and ensure your code is well formatted? I believe you'll need to change the assertion to
```python
assert isinstance(X, torch.Tensor)
```

**Comment by fehiepsi** [comment]
I thought that it was recommended to use `torch.is_tensor(x)` but looking at its docs again, it recommends to use `is_instance(...)` pattern.

**Comment by GautamV234** [comment]
> Can you `make lint` and ensure your code is well formatted? I believe you'll need to change the assertion to
> 
> ```python
> assert isinstance(X, torch.Tensor)
> ```

Sure I will do that and resubmit

**Comment by GautamV234** [comment]
I have modified all the files (added assertion checks) having this problem in the pyro/contrib/gp/models folder

Below is an example that illustrates the assertion error.

```py 
import pyro
import pyro.contrib.gp as gp
import numpy as np
import torch 
X = np.random.randn(200, 2)
Y = np.logical_xor(X[:, 0] > 0, X[:, 1] > 0).astype(np.float64) 
kernel = gp.kernels.RBF(input_dim=2)
likelihood = gp.likelihoods.Binary()
model = gp.models.VariationalGP(X, Y, kernel, likelihood=likelihood, whiten=True)

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Input In [6], in <cell line: 11>()
      9 kernel = gp.kernels.RBF(input_dim=2)
     10 likelihood = gp.likelihoods.Binary()
---> 11 model = gp.models.VariationalGP(X, Y, kernel, likelihood=likelihood, whiten=True)

File C:\work\Pyro\pyro\pyro\contrib\gp\models\vgp.py:74, in VariationalGP.__init__(self, X, y, kernel, likelihood, mean_function, latent_shape, whiten, jitter)     63 def __init__(
     64     self,
     65     X,
   (...)
     72     jitter=1e-6,
     73 ):
---> 74     assert isinstance(
     75         X, torch.Tensor
     76     ), "X needs to be a torch Tensor instead of a {}".format(type(X))
     77     assert isinstance(
     78         y, torch.Tensor
     79     ), "y needs to be a torch Tensor instead of a {}".format(type(y))
     80     super().__init__(X, y, kernel, mean_function, jitter)

AssertionError: X needs to be a torch Tensor instead of a <class 'numpy.ndarray'>
```
Please let me know if some tests need to be added pertaining to the updated code.

**Comment by GautamV234** [comment]
Hi there! I have been facing some issues while running the make lint command and would be great if you could look into it and let me know how I should proceed. PFA the screenshot of the issue. Thanks in advance.
image


> Thanks for adding the checks! I think no need to add tests. Pyro is based on PyTorch, not numpy, so we would expect all inputs are torch tensors.
> 
> Could you fix the lint issue? You can run `make lint`, `make format` to catch and fix the issues.

**Comment by GautamV234** [comment]
> Run `make format` and push

Thanks for the help!

**Review by fehiepsi — APPROVED** [review]
Thanks, @GautamV234 !

**Pull request merged**
