### PR TITLE
Expose initialization strategy in HMC

### PR DESCRIPTION
**Pull request by fehiepsi**
Addresses part of https://github.com/pyro-ppl/pyro/issues/2415.

There is one issue is: if users want to change keywords of init strategies, they have to use `partial`, e.g. `partial(init_to_median, num_samples=20)`. I find that it is a bit inconvenient for users. In NumPyro, users can set `init_strategy=` `init_to_median(20)` or `init_to_uniform(3)`, `init_to_value({"x": 10})`, `init_to_feasible()`.

### CODE REVIEW

**Comment by fehiepsi** [comment]
@fritzo `initial_params` is originally useful when users use `potential_fn` instead of `model`.

> Re: usability, you could use the standard poutine trick:

Thanks, yeah we should do it!

**Comment by fehiepsi** [comment]
> Do I understand correctly that this allows me to specify a subset of init_params to do so in the constrained space

Yes, you just need to specify a subset. The remaining params use the `uniform` strategy (default in MCMC).

**Comment by neerajprad** [comment]
@fritzo - does this address your concern of initialization code being triggered at various points in the flow despite the user specifying initial params?

**Comment by fehiepsi** [comment]
@neerajprad This does not. I think we should address it.

**Comment by fehiepsi** [comment]
I am fixing some typos. I'll address that too.

**Comment by neerajprad** [comment]
Thanks for clarifying, @fehiepsi. That might involve some refactoring, look forward to seeing your PR. Let me know if I can help.

**Comment by fritzo** [comment]
> does this address your concern of initialization code being triggered

Yes this partially addresses it. The problem was, the model was running 100 random initializations even if I provided a single good one. After This PR, if I provide a single good initialization through `init_to_value`, no random initializations are sampled.

**Pull request merged**
