### PR TITLE
Debugging torch=1.11 related pyro.contrib.funsor tests

### LINKED ISSUE #3046: Some pyro.contrib.funsor tests are failing in torch==1.11.0
This issue records tests of `pyro.contrib.funsor` that started failing in #3045. In that PR I've xfailed the following tests so as to unblock that PR.
- [ ] `python examples/contrib/funsor/hmm.py --num-steps=1 --truncate=10 --model=5 --funsor`
- [ ] `pytest -x tests/contrib/funsor/test_enum_funsor.py::test_elbo_enumerate_plate_1`
- [ ] `pytest -x tests/contrib/funsor/test_enum_funsor.py::test_elbo_enumerate_plate_4`
- [ ] `pytest -x tests/contrib/funsor/test_enum_funsor.py::test_elbo_enumerate_plate_6`
- [ ] `pytest -x tests/contrib/funsor/test_enum_funsor.py::test_elbo_enumerate_plate_7`
- [ ] `pytest -x tests/contrib/funsor/test_enum_funsor.py::test_elbo_enumerate_plates_2`
- [ ] `pytest -x tests/contrib/funsor/test_enum_funsor.py::test_elbo_enumerate_plates_3`
- [ ] `pytest -x tests/contrib/funsor/test_enum_funsor.py::test_elbo_enumerate_plates_4`
- [ ] `pytest -x tests/contrib/funsor/test_enum_funsor.py::test_elbo_enumerate_plates_5`
- [ ] `pytest -x tests/contrib/funsor/test_enum_funsor.py::test_elbo_enumerate_plates_6`
- [ ] `pytest -x tests/contrib/funsor/test_enum_funsor.py::test_elbo_enumerate_plates_7`
- [ ] `pytest -x tests/contrib/funsor/test_enum_funsor.py::test_elbo_enumerate_plates_8`

cc @eb8680 @ordabayevy

### PR DESCRIPTION
**Pull request by ordabayevy**
Resolves #3046

### CODE REVIEW

**Review by fehiepsi — APPROVED** [review]
Seems like things are green. ;)

**Comment by ordabayevy** [comment]
Yup, all tests passed locally and seem to pass here as well.

**Comment by fritzo** [comment]
Wait, did you simply remove all the xfails? I don't understand why things were failing on my system and on ci. Maybe something else changed?

**Review by fritzo — APPROVED** [review]

**Comment by fritzo** [comment]
Well thanks @ordabayevy, this is embarrassing since I don't know why tests were failing in the first place 😊

**Pull request merged**
