### PR TITLE
Bump version to 1.8.1

### PR DESCRIPTION
**Pull request by fritzo**
In preparation for 1.8.1 release:
- update version checks in notebooks to 1.8.1
- update funsor pinned version to 0.4.3
- xfailed a bunch of pyro.contrib.funsor enumeration tests #3046

### CODE REVIEW

**Comment by fritzo** [comment]
Looks like we're seeing #3046 again with `funsor==0.4.3`. @ordabayevy to try to get tests to pass I've reverted #3048 (which had simply removed xfails)

**Comment by fritzo** [comment]
Indeed git bisect shows the offending commit is @eb8680's and my https://github.com/pyro-ppl/funsor/pull/584

**Comment by eb8680** [comment]
It looks like re-running the tests made them pass? There were at least a couple tests off by a factor of 2 rather than numerical error, which is odd. I'll look into the failures this evening. I don't think it's worth blocking a Pyro release on `contrib.funsor` bugs though - I'd be OK with either releasing as-is with some tests marked xfail or reverting the change in Funsor. I'll look into the failures tonight.

**Comment by fritzo** [comment]
@eb8680 the tests passed because I xfailed them 😊  LMK if you want to pair debug on our funsor PR. I'm ok either reverting that PR or releasing pyro with some contrib.funsor bugs, but I'd prefer to do a quick bugfix release of funsor 0.4.4 if we can find & fix the error. It took so long to get that PR merged...

**Comment by fritzo** [comment]
@fehiepsi, @eb8680 are ok merging this with the xfailed tests in contrib.funsor and we can look into fixing those tests later. I think the PyTorch update is higher priority.

**Review by martinjankowiak — APPROVED** [review]

**Pull request merged**
