### PR TITLE
Make Loss negative (#1982)

### LINKED ISSUE #1982: [bug] TraceGraph_ELBO inconsistent in sign of ELBO
### Issue Description
 + `TraceGraph_ELBO.loss()` returns the negative ELBO (as expected).
 + `TraceGraph_ELBO.loss_and_grads()` returns the positive ELBO.

This doesn't affect the optimisation as the surrogate loss is based on the negative ELBO, but is confusing when monitoring convergence. May well happen in other ELBO classes, this is just the one that I've been using and hence spotted it in.

### Environment
MacOS, Python 3.7.1, PyTorch 1.1.0, Pyro 0.3.4

### PR DESCRIPTION
**Pull request by JamesTrick**
Resolves #1982.

This short PR changes the sign on the ELBO loss in the `TraceGraph_ELBO.loss_and_grads()` function.

I was a bit more explicit than just changing the sign in the return statement trying to be consistent with `TraceGraph_ELBO.loss()`. Happy for any feedback :)

### CODE REVIEW

**Comment by JamesTrick** [comment]
Perfect, thanks so much @fritzo. Adding that test has caused quite a few failures, so I'll work through them over the weekend :).

**Comment by fritzo** [comment]
Don't hesitate to ask for help with the failures :smile: And thanks again for taking on this fix!

**Comment by JamesTrick** [comment]
Hi @fritzo 

Work on this is getting close (I think). With the regression test now comparing `loss` and `loss_and_grad` outputs I'm finding I'm getting test failures where the losses are significantly different and seem unrelated to the sign difference. An example would be below:

```python
Elbo = <class 'pyro.infer.traceenum_elbo.TraceEnum_ELBO'>

    @pytest.mark.parametrize("Elbo", [Trace_ELBO, TraceGraph_ELBO, TraceEnum_ELBO])
    def test_vectorized_num_particles(Elbo):
        data = torch.ones(1000, 2)
    
        def model():
            with pyro.plate("components", 2):
                p = pyro.sample("p", dist.Beta(torch.tensor(1.1), torch.tensor(1.1)))
                assert p.shape == torch.Size((10, 1, 2))
                with pyro.plate("data", data.shape[0]):
                    pyro.sample("obs", dist.Bernoulli(p), obs=data)
    
        def guide():
            with pyro.plate("components", 2):
                pyro.sample("p", dist.Beta(torch.tensor(1.1), torch.tensor(1.1)))
    
        pyro.clear_param_store()
        guide = config_enumerate(guide) if Elbo is TraceEnum_ELBO else guide
        assert_ok(model, guide, Elbo(num_particles=10,
                                     vectorize_particles=True,
                                     max_plate_nesting=2,
>                                    strict_enumeration_warning=False))

tests/infer/test_valid_models.py:1301: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/infer/test_valid_models.py:41: in assert_ok
    assert_close(loss_and_grads, loss, atol=0.01)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

actual = 1796.482041801836, expected = 2962.027828897718, atol = 0.01, rtol = 0, msg = '1796.482041801836 vs 2962.027828897718'

    def assert_close(actual, expected, atol=1e-7, rtol=0, msg=''):
        if not msg:
            msg = '{} vs {}'.format(actual, expected)
        if isinstance(actual, numbers.Number) and isinstance(expected, numbers.Number):
>           assert actual == approx(expected, abs=atol, rel=rtol), msg
E           AssertionError: 1796.482041801836 vs 2962.027828897718
```
Any advice on where to start to look to try identify the cause would be great! There are about 11 cases in total. Part of me thinks this difference is OK and perhaps refactoring the test to check for where the signs are different may work. I don't quite understand `loss_and_grads` to make that call.

**Comment by fritzo** [comment]
Awesome progress!

Re: failing tests, My guess is that the test I gave you is impossible to satisfy :smile: because each expression is randomized. One thing we could try is setting the random seed before each invocation:
```diff
+ pyro.set_rng_seed(0)
  loss = elbo.loss(model, guide, **kwargs)
  if hasattr(elbo, "differentiable_loss"):
      try:
+       pyro.set_rng_seed(0)
  	differentiable_loss = elbo.differentiable_loss(model, guide, **kwargs).detach().cpu().item()
      except ValueError as e:
  	pass # Ignore cases where elbo cannot be differentiated 
      else:
  	assert_close(differentiable_loss, loss)
  if hasattr(elbo, "loss_and_grads"):
+     pyro.set_rng_seed(0)
      loss_and_grads = elbo.loss_and_grads(model, guide, **kwargs)
      assert_close(loss_and_grads, loss)

```
If that doesn't work, we could simply try writing less generic tests.

**Comment by fritzo** [comment]
Hi @JamesTrick, thanks for keeping on this, it seems to be more work than either of us expected.

I think `Trace_ELBO` is free of sign error. In fact I am seeing `test_valid_models.py` pass with just a few changes to your last commit:
```diff
diff --git a/pyro/infer/trace_elbo.py b/pyro/infer/trace_elbo.py
index f37db024..618563f1 100644
--- a/pyro/infer/trace_elbo.py
+++ b/pyro/infer/trace_elbo.py
@@ -108,7 +108,7 @@ class Trace_ELBO(ELBO):
             surrogate_loss += surrogate_loss_particle / self.num_particles
             loss += loss_particle / self.num_particles
         warn_if_nan(surrogate_loss, "loss")
-        return loss + (surrogate_loss - surrogate_loss.detach())
+        return loss + (surrogate_loss - torch_item(surrogate_loss))

     def loss_and_grads(self, model, guide, *args, **kwargs):
         """
@@ -133,7 +133,6 @@ class Trace_ELBO(ELBO):
                 surrogate_loss_particle = surrogate_loss_particle / self.num_particles
                 surrogate_loss_particle.backward(retain_graph=self.retain_graph)

-        loss = -loss
         warn_if_nan(loss, "loss")
         return loss

diff --git a/tests/infer/test_valid_models.py b/tests/infer/test_valid_models.py
index fc072deb..35928c50 100644
--- a/tests/infer/test_valid_models.py
+++ b/tests/infer/test_valid_models.py
@@ -11,6 +11,7 @@ import pyro.poutine as poutine
 from pyro.distributions.testing import fakes
 from pyro.infer import (SVI, Trace_ELBO, TraceEnum_ELBO, TraceGraph_ELBO, TraceMeanField_ELBO, TraceTailAdaptive_ELBO,
                         config_enumerate)
+from pyro.infer.util import torch_item
 from pyro.ops.indexing import Vindex
 from pyro.optim import Adam
 from tests.common import assert_close
@@ -33,7 +34,7 @@ def assert_ok(model, guide, elbo, **kwargs):
         if hasattr(elbo, "differentiable_loss"):
             try:
                 pyro.set_rng_seed(0)
-                differentiable_loss = elbo.differentiable_loss(model, guide, **kwargs).detach().cpu().item()
+                differentiable_loss = torch_item(elbo.differentiable_loss(model, guide, **kwargs))
             except ValueError as e:
                 pass # Ignore cases where elbo cannot be differentiated
             else:
```

**Comment by JamesTrick** [comment]
Thanks @fritzo! I realised the same thing last night that Trace_ELBO was free from error. I was still getting the sign error for TraceGraph, I'll push that change in about an hour when I have my laptop.

**Comment by fritzo** [comment]
@JamesTrick thanks again for submitting this fix!

**Pull request merged**
