### PR TITLE
Support plates in RenyiELBO

### PR DESCRIPTION
**Pull request by fritzo**
Addresses #2220 
Pair coded with @martinjankowiak 

This adds plate support to `RenyiELBO`. Once this merges, similar changes can be applied to `TraceAdaptiveTail_ELBO` and `ReweightedWakeSleep`.

## Tested
- [x] strengthened inference tests
- [x] added weak tests with various batch shapes
- ... other test suggestions welcome...

### CODE REVIEW

**Comment by fritzo** [comment]
cc @tuananhle7 @iffsid

**Comment by iffsid** [comment]
cool, thanks!
We'll setup a PR once this merges. :)

**Comment by fehiepsi** [comment]
The change looks reasonable to me. Just to verify my understanding, to support the previous behavior, I should declare different plates for z and x?
```
def model():
    with pyro.plate('z', 2):
        pyro.sample('z', ...)
    with pyro.plate('x', 2):
        pyro.sample('x', ...)
```

**Comment by fritzo** [comment]
@fehiepsi yes good point, you can indeed declare different plates to achieve previous behavior.

**Pull request merged**
