### PR TITLE
miscellaneous updates to svi part i tutorial

### PR DESCRIPTION
**Pull request by martinjankowiak**
- add some links to docs
- add a new reference
- add a missing `log`
- fix text describing use of param-specific optimizer hypers

### CODE REVIEW

**Comment by martinjankowiak** [comment]
any idea how to fix a broken list in svi_part_ii? search for "point-by-point" [here](http://pyro.ai/examples/svi_part_ii.html) to see what i mean

**Comment by martinjankowiak** [comment]
i also get a `pyro/tutorial/source/RSA-hyperbole.ipynb:7:Unexpected indentation.` when trying to build the tutorials. can anyone reproduce this? is there something to fix in the notebook?

**Review by fritzo — APPROVED** [review]
LGTM.  I think it's probably cleaner to avoid the `?highlight=...` query in links, but not worth blocking review.

**Comment by fritzo** [comment]
> how to fix a broken list in svi_part_ii?

It probably needs two newlines (not just one) between the previous paragraph and the first bullet point.

> RSA-hyperbole.ipynb:7:Unexpected indentation

Weird, I cannot reproduce on my machine.

**Pull request merged**
