### PR TITLE
Fix math expressions for latex pdf docs.

### PR DESCRIPTION
**Pull request by ljlin**
I was trying to get a pdf version of the docs and the tutorial by running the following command.

```sh
make -C docs latex    
make -C tutorial latex
```
And I encounter some minor issues like:

1. extra `\\` in `\\D` ( see [this page](https://docs.pyro.ai/en/1.6.0/contrib.timeseries.html#pyro.contrib.timeseries.gp.LinearlyCoupledMaternGP)),
2. LaTex complains about `\rm{reco}` in [vae.ipynb](https://github.com/pyro-ppl/pyro/blob/98ed9f15f96734c51ea961722a3d46e73c1ce878/tutorial/source/vae.ipynb), and
3.  LaTex complains about multiline aligned equations. (eg., `$$ \begin{align}  ... \end{align} $$` in [ss-vae.ipynb](https://github.com/pyro-ppl/pyro/blob/98ed9f15f96734c51ea961722a3d46e73c1ce878/tutorial/source/ss-vae.ipynb))

I tried to solve (3) by removing double dollars according to [this comment](https://github.com/spatialaudio/nbsphinx/issues/357#issuecomment-557228334), but `Sphinx` threw an error.

```
Running Sphinx v4.0.1
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: [new config] 73 added, 0 changed, 0 removed
reading sources... [100%] working_memory                                                         
waiting for workers...

Warning, treated as error:
~/Projects/pyro/tutorial/source/ss-vae.ipynb:332:Inline interpreted text or phrase reference start-string without end-string.
make: *** [latex] Error 2
```

So I keep these double dollars and got things like

```latex
\begin{equation*}
\begin{split}\begin{align}
...
\end{align}\end{split}
\end{equation*}
```

in `/tutorial/build/latex/PyroTutorials.tex`. Then I manually fix LaTex errors for `PyroTutorials.tex` and got [Pyro.pdf](https://github.com/pyro-ppl/pyro/files/6471394/Pyro.pdf) and [PyroTutorials.pdf](https://github.com/pyro-ppl/pyro/files/6471397/PyroTutorials.pdf) in the end.

I was wondering whether there is a better and automatic way to do this? Thanks for your time.

### CODE REVIEW

**Review by fehiepsi — DISMISSED** [review]
The changes look good to me. Thanks, @ljlin!

**Comment by fritzo** [comment]
@ljlin if you're still having trouble you could try to replace
```
$$
\begin{align}
\end{align}
$$
```
with
```
\begin{aligned}
\end{aligned}
```
since `align` is to be used within the math environment, whereas `aligned` is used within text.

**Comment by ljlin** [comment]
Yes, there are still several `$$\begin{align} ... \end{align}$$` in `normalizing_flows_i.ipynb` and `ss-vae.ipynb`.

@fritzo Thanks for your suggestions. By doing so, I ended up with a LaTex source file that also requires minor manual fixes.

```
[Compiling ~/Projects/pyro/tutorial/build/latex/PyroTutorials.tex]

TraditionalBuilder: Engine: xelatex. Invoking latexmk... done.

Errors:

~/Projects/pyro/tutorial/build/latex/PyroTutorials.tex:6770: Package amsmath Error: \begin{aligned} allowed only in math mode. [    \mathcal]
~/Projects/pyro/tutorial/build/latex/PyroTutorials.tex:6770: Missing $ inserted. [    \mathcal]
~/Projects/pyro/tutorial/build/latex/PyroTutorials.tex:6772: Missing $ inserted. [\end{aligned}]
...
```

I believe there is a typo in your last comment,

> `align` is to be used within the math environment, whereas `aligned` is used within text.

should be

>`aligned` is to be used within the math environment, whereas `align` is used within text.

according to section 3.6 and 3.7 of [amsmath doc](https://mirrors.sustech.edu.cn/CTAN/macros/latex/required/amsmath/amsldoc.pdf).

**Comment by fritzo** [comment]
@ljlin you are right, I guess the `$$` around `align` are thus redundant 🤔  Thanks for looking into this...

**Comment by fehiepsi** [comment]
I faced this issue previously and resolved it by [removing `$$` signs](https://github.com/pyro-ppl/numpyro/pull/803/files#diff-70b40bb0c6131288501196fa21b34e825be987a394fbbdbbc1b3f1619e277dc2). Probably we need to change something in the formula to bypass the error.

**Review by fehiepsi — APPROVED** [review]
@ljlin Is this ready to merge?

**Comment by ljlin** [comment]
Hi, @fehiepsi Yes, I believe this is ready to merge since trouble (1), (2), and (3) are both solved. The generated `*.tex` files are almost perfect, there's no compilation error (`Sphinx v3.5.4`, `XeTeX 3.14159265-2.6-0.999991 TeX Live 2019`, `macOS Big Sur 11.2.3 (20D91)`).

But there are still minor things that may lead to another PR/issue
- (i) NO-BREAK SPACE (`U+00A0`) turns into `ă` under XeLaTeX
- (ii) LaTex targets are not added to `Makefile`/test/CI.

I guess (i) is more like a `sphinx` issue, and we would like to ignore it for now. And (ii) is up to repository maintainers (maybe at a later time).

**Comment by fehiepsi** [comment]
Thanks, @ljlin! Generating pdf is optional so we might not need to add it to CI. :)

**Pull request merged**
