### PR TITLE
Separate requirements.txt file

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Comment by neerajprad** [comment]
Could you elaborate on the motivation for having a `requirements.txt` file; in particular, are there any tasks / workflows which this facilitates? My understanding is that it is more useful for applications to have `requirements.txt` to pin dependencies to specific versions, but since Pyro is a library, we have typically left it to our users to define their concrete dependencies as they see fit in their own `requirements.txt` for as long is it meets our minimum requirements. Just looking to understand, the proposed change looks good otherwise.

**Comment by gliptak** [comment]
@neerajprad a ```requirements.txt``` can be used by your contributors (and maybe build system) to ```pip``` install dependencies

**Comment by neerajprad** [comment]
> @neerajprad a requirements.txt can be used by your contributors (and maybe build system) to pip install dependencies

How about just `pip install -e .` for locally installing? Even just having `-e .` in the `requirements.txt` file should work. If there are build tools that require an explicit set of dependencies, then I can see the need for this. I can see that another use might just be to keep our `docs/requirements.txt` in sync by symlinking it to this. What do you think @jpchen, @fritzo?

**Comment by fritzo** [comment]
Unless there are compelling use cases, I think it's cleanest to avoid duplication of logic in both setup.py and requrements.txt. As @neerajprad mentioned, `pip install -e .` satisfies the only use case I can think of. @gliptak can you be more specific about use cases you would like to support?

**Comment by gliptak** [comment]
Thanks for the pointers. Closing at this time

**Pull request closed without merging**
