### PR TITLE
Test github actions for CI

### PR DESCRIPTION
**Pull request by neerajprad**
- [x] existing test stages should pass.
 - [x] add coveralls to aggregate coverage info from all stages.
 - [x] add funsor tests from #2583

Removed some stages from travis like profiling which we weren't using. Those can still be run locally.

Updates:
 - [x] Update version of python/pytorch and torchvision.
 - [x] Add mypy to lint.

### CODE REVIEW

**Comment by neerajprad** [comment]
@fritzo - This branch is working fine and we can merge this whenever we want to get off travis.

**Comment by neerajprad** [comment]
Current status: We have a dependency on [lap](https://github.com/gatagat/lap) (not sure about the full dependency chain) but building the wheel fails with:

```
  error: Command "g++-8 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/numpy/core/include -Ilap -I/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/numpy/core/include -I/opt/hostedtoolcache/Python/3.6.13/x64/include/python3.6m -c lap/lapjv.cpp -o build/temp.linux-x86_64-3.6/lap/lapjv.o -MMD -MF build/temp.linux-x86_64-3.6/lap/lapjv.o.d" failed with exit status 127
```

. I have tried a few things based on some google results but haven't made progress.  @fehiepsi: let me know if you have seen something like this before.

**Comment by fritzo** [comment]
We can safely drop the dependency on lap (i.e. make it an optional dependency as we do in many places). It is used only in the esoteric `SpanningTree.mode()` method.

**Comment by fritzo** [comment]
@neerajprad I'll take a look at the `lap` issue...

**Review by fritzo — APPROVED** [review]

**Comment by neerajprad** [comment]
I will follow this up by moving some of the install steps to make later. Right now, github actions doesn't provide support for templates so the yaml file is more verbose with duplicated steps.

**Review by fritzo — APPROVED** [review]

**Review by fehiepsi — APPROVED** [review]

**Comment by fehiepsi** [comment]
Happy to merge and unblock other PRs. Thanks, @neerajprad and @fritzo!

**Pull request merged**
