### PR TITLE
Add logistic growth tutorial

### PR DESCRIPTION
**Pull request by martinjankowiak**
[open in colab](https://colab.research.google.com/github/pyro-ppl/pyro/blob/add-logistic-growth-tut/tutorial/source/logistic-growth.ipynb)

### CODE REVIEW

**Comment by martinjankowiak** [comment]
our notebooks assume that pyro is installed which is not the case for colab. do we just make a second copy of the notebook that has the `pip install` at the top?

**Comment by martinjankowiak** [comment]
- typo: +to => "Next let's extract sublineages corresponding two of the"
- arguably `rate_scale` isn't doing much in the last model since there are only two lineages
- typo: generalization section => "usepyro.plate"

generally looks great and i think this will be a good fit for the workshop

**Review by fritzo — APPROVED** [review]
Thanks for making this @martinjankowiak!

**Comment by martinjankowiak** [comment]
thank for your substantial improvements!

**Pull request merged**
