### PR TITLE
Forecast DLM tutorial

### PR DESCRIPTION
**Pull request by edwinnglabs**
I just write a DLM tutorial.  Please let me know if I need to fix anything.

See [notebook](https://nbviewer.jupyter.org/github/edwinnglabs/pyro/blob/forecast-dlm-test/tutorial/source/forecasting_dlm.ipynb)

## Tasks

- [x] #2636 get `HaarReparam` to work with `pyro.contrib.forecast`
- [x] #2632 make it easier to examine posterior samples of latent variables

### CODE REVIEW

**Comment by fritzo** [comment]
@edwinnglabs can you push your latest changes? I'd like to try simplifying but I'd like to avoid merge conflict.

**Comment by edwinnglabs** [comment]
> @edwinnglabs can you push your latest changes? I'd like to try simplifying but I'd like to avoid merge conflict.

i just updated the notebook. let me know if you need anything else.

**Comment by edwinnglabs** [comment]
Looks like those two tasks are done. What's the current status?

**Comment by fritzo** [comment]
You could update and merge pyro dev branch into this branch. Then you should be able to try out [new options](http://docs.pyro.ai/en/latest/contrib.forecast.html#pyro.contrib.forecast.forecaster.Forecaster) `Forecaster(..., time_reparam="haar")` and  `Forecaster(..., time_reparam="dct")

**Comment by edwinnglabs** [comment]
If you're updating the notebook anyway, I can wait for the update from your side.

**Comment by fritzo** [comment]
@edwinnglabs I've updated the notebook. I tried both Haar and DCT reparam but they didn't seem to work well.

**Review by fritzo — COMMENTED** [review]
Looks good, I have only cosmetic comments, then this should be ready to merge:
- [ ] eliminate unused imports
- [ ] replace numpy random generation with torch. I think this should work:
    ```py
    beta0 = torch.empty(n, 1).normal_(0, 0.3)
    betas_p = torch.empty(n, p, 1).normal_(0, 0.05).cumsum(0)
    ```
- [ ] typo: vanila -> vanilla
- [ ] In the model `DLM2` can you clearly separate the prior injection and add some comments highlighting that "This is the only change from the simpler DLM model. We inject prior terms as if they were likelihoods using pyro observe statements."
- [ ] Rewrite conclusion in paragraph form and check for grammar.
- [ ] Change references to an enumeration list (1. 2. 3.) and reference at least one paper in the intro.
- [ ] It would be nice to have a little sentence between each section heading and the next code block, just to explain what you're doing.

After these changes and we merge, I'll add to the index and try to add to CI.

**Comment by edwinnglabs** [comment]
@fritzo feel free to double check the changes match what you expect for those check boxes.

**Review by fritzo — APPROVED** [review]
Looks great! We'll publish this on pyro.ai/examples at the next release (in a few weeks).

**Pull request merged**
