### PR TITLE
adding quantiles method to AutoGuideList

### PR DESCRIPTION
**Pull request by vitkl**
This pull request adds quantiles method to AutoGuideList. I did not find where a test for this can be added. Please let me know what you think.

### CODE REVIEW

**Comment by fehiepsi** [comment]
@vitkl You can add a test [here](https://github.com/pyro-ppl/pyro/blob/43c037443a05223b27e945fea26b2d4c2a0d79d8/tests/infer/test_autoguide.py#L402). :)

**Comment by fritzo** [comment]
This is great.  Can you resolve lint errors and add a test case?
```py
/pyro/infer/autoguide/guides.py:270:1: W293 blank line contains whitespace
```

**Comment by vitkl** [comment]
For `AutoLaplaceApproximation` guides, AutoGuideList also needs a method `guide.laplace_approximation()` - but otherwise, I added tests. 

Do you use pre-commit for enforcing the code style?

**Comment by fritzo** [comment]
@vitkl you can `make lint` to test linting locally.

**Comment by fritzo** [comment]
@vitkl I believe you need to switch the docstring from numpy-style to sphinx rst style:
```
"""
Returns the posterior quantile values of each latent variable.

:param list quantiles: A list of requested quantiles between 0 and 1.
:returns:A dict mapping sample site name to quantiles tensor.
:rtype: dict
"""
```

**Review by fritzo — COMMENTED** [review]
Hi @vitkl I think you'll just need to merge with the dev branch, since we switched CI systems.  Looking forward to merging this!

**Comment by fritzo** [comment]
Hi @vitkl, this is a great new feature to have, and I'd like to include it in the next release. Do you want any help getting this merged?

**Comment by vitkl** [comment]
When do you plan next release?

**Comment by fritzo** [comment]
> When do you plan next release?

Oh, how about next Wednesday 7/7?  There's no fixed deadline, but I'd like to get out fixes for PyTorch 1.9 by the end of next week.

**Comment by fritzo** [comment]
Hi @vitkl no pressure, but do you plan to update this branch today?  If not I'll release without, since there is a pressing PyTorch bug workaround.  Also I'm happy to take over this PR and get your feature in if you're busy.

**Comment by vitkl** [comment]
Hi Fritz

Sorry, still occupied by paper revision. I can't make it today. If you can
take over would be great otherwise I will do it in ~2 weeks!

**Comment by vitkl** [comment]
Hm, actually, as I look at it now - I think I have addressed it comments from @fritzo and @fehiepsi . What remains is fixing the conflict on this branch (which I don't immediately understand) and merging it to the correct branch. Would be great if you can do that.

**Comment by fritzo** [comment]
Closing after moving to #2896

**Pull request closed without merging**
