### PR TITLE
add ProdLDA tutorial

### PR DESCRIPTION
**Pull request by martinjankowiak**
this tutorial has been slightly adapted from @ucals 's excellent work in #2655.

most of the changes are textual improvements but i also added smoke_test support for CI integration.

### CODE REVIEW

**Comment by eb8680** [comment]
Thanks for updating this!
- Could we replace `LogNormal` with `Dirichlet` and drop the corresponding discussion about reparametrization, or is it better to stick closely to the content of the paper?
- Did you want to make the other changes you suggested in https://github.com/pyro-ppl/pyro/pull/2655#issuecomment-706618876?
- Use consistent names for the two neural networks throughout, in both text and code (e.g. always call them `encoder`/`decoder`), and avoid using "recognition net" for the decoder?

**Comment by martinjankowiak** [comment]
thanks @eb8680 
- re: dirichlet i think it's best to stick to the paper (but i added a comment)
- tried to use encoder/decoder everywhere please check for consistency
- added more figure captions
- didn't add `poutine.scale` logic since it it's apparently stable

**Review by eb8680 — DISMISSED** [review]

**Comment by eb8680** [comment]
Can you also double-check that everything renders correctly in Sphinx?

**Comment by martinjankowiak** [comment]
not sure my sphinx build dies on `mle_map.ipynb` 🤷‍♀️

**Comment by eb8680** [comment]
Looks like a bug introduced in #2701, try with the change in #2730?

**Comment by eb8680** [comment]
Can you also add an attribution to @ucals at the top, below the title? ("This tutorial was originally written by @ucals" or something to that effect)

**Comment by martinjankowiak** [comment]
ok thanks @eb8680 merged your fix rendering looks fine

**Review by eb8680 — APPROVED** [review]

**Pull request merged**
