### PR TITLE
Release patch to fix mcmc parallel chains using multiprocessing

### PR DESCRIPTION
**Pull request by neerajprad**
~~Blocked by https://github.com/pyro-ppl/pyro/pull/2270~~

### CODE REVIEW

**Comment by fritzo** [comment]
Will your release include the recent tutorial fixed?

**Comment by neerajprad** [comment]
> Will your release include the recent tutorial fixed?

I was thinking of including all the tutorial fixes too. We can also just patch this atop the last release. WDYT>

**Comment by fritzo** [comment]
Sure, go ahead and release these fixes any time.

**Comment by neerajprad** [comment]
Let us try to get https://github.com/pyro-ppl/pyro/issues/2270 in too.

**Comment by fritzo** [comment]
@neerajprad ready to merge?

**Comment by neerajprad** [comment]
Yes, ready to merge.

**Pull request merged**
