### PR TITLE
Simple change to make DiagNormal and BNAF be plotted side-by-side

### PR DESCRIPTION
**Pull request by randommm**
A simple change to make DiagNormal and BNAF be plotted side-by-side, this way it's easier to visualize the results.

### CODE REVIEW

**Comment by fehiepsi** [comment]
Thanks, @randommm! Could you include a screenshot for the change?

**Comment by randommm** [comment]
New version

Screenshot at 2020-09-12 13-22-21

**Comment by randommm** [comment]
Old version

Screenshot at 2020-09-12 13-26-52

**Review by fehiepsi — APPROVED** [review]
Thanks @randommm!! The change is clearly better.

**Pull request merged**
