### PR TITLE
Add cheap test for log joint computation in neutra reparametrizer

### PR DESCRIPTION
**Pull request by neerajprad**
I have been trying to understand why the results from neutraHMC are sub par on a few examples that I have tried out, and this test is to just validate the log joint computation (which looks fine). I am still debugging other issues with the example.

### CODE REVIEW

**Comment by fritzo** [comment]
Test looks reasonable, but is there a way to check for sign errors in e.g. the `log_abs_det_jacobian`?  I guess you could flip the sign in the implementation and check that results are even worse 🤔

**Comment by neerajprad** [comment]
> Test looks reasonable, but is there a way to check for sign errors in e.g. the log_abs_det_jacobian?

I tried that but didn't see any improvements. The guide is actually learning something useful but running HMC on the warped space seems to take a long time and the samples look particularly bad. I might add more tests during the course of debugging, thanks for the tip!

**Comment by fehiepsi** [comment]
> running HMC on the warped space seems to take a long time

I think the slowness is expected. There might be some discontinuities in log_prob computation. Did you try BNAF instead of IAF? (I didn't have any success with iaf :(

**Comment by neerajprad** [comment]
> I think the slowness is expected. There might be some discontinuities in log_prob computation. Did you try BNAF instead of IAF? (I didn't have any success with iaf :(

I'll update the other PR so that you can follow where I am up. I have even simplified to using a single mode banana gaussian distribution (with a multi-modal distribution, results can be pretty random when fitting the guide since SVI can choose to focus on only one of the modes, so I wanted to test with a simpler setting). With that, IAF does a pretty reasonable job of fitting (not in the tails though), and I ideally wanted to see HMC fill out the tails, but the results are quite terrible with the samples falling along one vertical line, and pointing to some more serious bug. I am not too concerned about the speed until this issue is rectified.

**Comment by fehiepsi** [comment]
Yup, let's try to isolate the issue. I can recall this [old issue](https://github.com/pyro-ppl/pyro/issues/1706#issuecomment-453151242) with discontinuity, which might be relevant. When you make the other PR, I will try to see if the issue happens with NumPyro.

**Comment by neerajprad** [comment]
Thanks, Du. I just created https://github.com/pyro-ppl/pyro/pull/2294 to discuss the issue.

**Pull request merged**
