### PR TITLE
Adding Probabilistic Topic Modeling tutorial

### PR DESCRIPTION
**Pull request by ucals**
This PR contributes with a Probabilistic Topic Modeling Tutorial. Thank you guys for all the help to put it together... it took way longer than what I thought it would take, but I think it is a nice tutorial. :)
Please let me know your thoughts/inputs/comments.. Cheers!

View [notebook](https://nbviewer.jupyter.org/github/ucals/pyro/blob/prodlda_tutorial/tutorial/source/prodlda.ipynb)

### CODE REVIEW

**Comment by fehiepsi** [comment]
Awesome tutorial, as always!

**Comment by martinjankowiak** [comment]
thanks carlos this is great! some initial feedback:

- i think you can safely shorten the motivation in the introduction (data deluge etc)
- give the figure a capture and attribution (i.e. reference where you got it from)
- define iid
- remove "If you don't have it installed, just run pip install scikit-learn to install it."
- typos "dictiorary", "comparisot"
- add some comments to the large module/model/guide codeblock
- always index from the right not left => ```theta = theta / theta.sum(1, keepdim=True)```
- if possible we should add some logic so that this can be run in CI (see other tutorial notebooks)
- there are a few places where language/grammar could be improved but i could do that in a follow-up PR once this is merged if you're OK with that

**Comment by ucals** [comment]
Thanks @martinjankowiak ! 
- [x] i think you can safely shorten the motivation in the introduction (data deluge etc)
- [x] give the figure a capture and attribution (i.e. reference where you got it from)
- [x] define iid
- [x] remove "If you don't have it installed, just run pip install scikit-learn to install it."
- [x] typos "dictiorary", "comparisot"
- [x] add some comments to the large module/model/guide codeblock
- [x] always index from the right not left => theta = theta / theta.sum(1, keepdim=True)
- [ ] if possible we should add some logic so that this can be run in CI (see other tutorial notebooks)
- [ ] there are a few places where language/grammar could be improved but i could do that in a follow-up PR once this is merged if you're OK with that

Implemented all but the last 2:
- Regarding adding some logic to run in CI: I noticed there are 3 types of tutorials. There are i) tutorials that explain some code contained in the `examples` folder (those have tests), ii) tutorials that are entirely self-contained in the `ipynb` file (I couldn't find any tests for those.. e.g. `bayesian_regression.ipynb`), and iii) code examples (the `rst` file just points to the `py` files in the `examples` folder, so they also have tests). The tutorials that are entirely self-contained don't have tests (or at least I couldn't find). So, as this tutorial is entirely self-contained (exactly as `bayesian_regression.ipynb`), I couldn't find any example to reapply the approach here.. Pls advise.
- Regarding language/grammar: sorry for that, English is (clearly) not my first language :) pls let me know what you think can be improved, and I'll work on that :)

Cheers

**Comment by martinjankowiak** [comment]
thanks @ucals ! some additional comments:

- see vae.ipynb (look for `smoke_test`) for CI testing logic (you can skip parts of the code in CI, eg the wordcloud code; actually this will be necessary because we don't want a wordcloud dependency)
- please add captions to the remaining figures
- can you replace the plate in the model and guide as follows:
```
import pyro.poutine as poutine
num_docs = docs.size(0)
scale = 1.0 / (num_docs * self.vocab_size) # or whatever you think a good normalization is
with pyro.plate("documents", num_docs), poutine.scale(scale=scale):
```
- regarding small languages changes don't worry about it i can do it in a follow-up PR (i just want to add the word 'the' in a few places etc)

**Comment by eb8680** [comment]
@martinjankowiak can we go ahead and merge this today so it's included in the 1.5 release?

**Comment by martinjankowiak** [comment]
i don't think there's any rush

**Comment by eb8680** [comment]
Ok, but I'd like it to be visible on the examples page for next week if possible

**Comment by ucals** [comment]
Hey guys, sorry for the late response... I'm completely swamped with work this week, can only implement the latest requests over the weekend...

**Comment by martinjankowiak** [comment]
@ucals no worries at all!

**Comment by martinjankowiak** [comment]
@ucals hi carlos, do you perhaps have time to push this across the finish line or would you prefer that we do it for you?

**Comment by ucals** [comment]
Hey @martinjankowiak ! Sorry, I'm very busy at work, unfortunately can't find time to finish... thx!

**Comment by martinjankowiak** [comment]
@ucals thanks again for your great tutorial! closing this in favor of #2729 . please let us know if you have any additional comments/suggestions!

**Pull request closed without merging**
