### PR TITLE
Render deterministic functions

### PR DESCRIPTION
**Pull request by r3v1**
Addresses #3134.

### CODE REVIEW

**Review by fritzo — COMMENTED** [review]
Hi @r3v1, thanks for taking on this task!  Could you describe your approach a bit in the PR description? 🙏 

It's been almost a year since I looked into this, but I recall one issue was that Pyro's visualization reuses inference machinery for tracking dependency, and the goals of these two uses are a bit at odds: in inference one wants to ignore deterministic dependencies and simply track stochastic latent variables because only those stochastic latent variables can be freely varied during inference. By contrast in visualization one often wants to inspect the model, including in many cases deterministic dependencies or even compute graphs.

Now again it's been a while but I think where I [left off on this task](https://github.com/pyro-ppl/pyro/compare/dev...render-deterministic), it seemed challenging to separate these two concerns, like we might need to fork some of the provenance tracking and maybe add some conditional flags so one could optionally trace deterministic nodes (for visualization) or optionally elide them (for inference). I'm not sure how you PR might address these issues, but I think it's worth examining before making changes that affect inference. 🙂

**Comment by r3v1** [comment]
Of course @fritzo, I could explain the process I have gone through.

First, I started by studying the unit tests and seeing what the `get_model_relations` function was expected to return depending on the model, which returned a dictionary representing a graph. Next, I started debugging inside that method the logic you had implemented and started to understand how the different parts "exchange messages" (dictionaries) and I noticed that everything resided inside the `apply_stack` call. 

When calling [`_post_process_message()`](https://github.com/r3v1/pyro/blob/537f7a071ec020855c3f56fe635ec10272261801/pyro/poutine/runtime.py#L221), it checks if the TrackProvenance object has a method `f"_pyro_post_{}".format(msg["type"])`, but as being `deterministic`, it was not implemented yet, so I need to [implement it](https://github.com/r3v1/pyro/blob/537f7a071ec020855c3f56fe635ec10272261801/pyro/infer/inspect.py#L63). To do it, I just remembered watching the same structured code somewhere in [Numpyro's code](https://github.com/pyro-ppl/numpyro/blob/6b2353427c21792b5b4bfcb01192bb408ee9944f/numpyro/infer/inspect.py#L363), so that's what I [applied](https://github.com/r3v1/pyro/blob/537f7a071ec020855c3f56fe635ec10272261801/pyro/infer/inspect.py#L63). In the same way, the [`_pyro_post_deterministic`](https://github.com/r3v1/pyro/blob/537f7a071ec020855c3f56fe635ec10272261801/pyro/poutine/trace_messenger.py#L140) of `TraceMessenger` was implemented.

Of course, the primitive `deterministic` should be modified to match the above. I just took another look to Numpyro's [`deterministic`](https://github.com/pyro-ppl/numpyro/blob/6b2353427c21792b5b4bfcb01192bb408ee9944f/numpyro/primitives.py#L283) to take some ideas. I noticed that their implementation differs, so I gave a try and implemented something similar. I ended up with the idea submitted, emulating the same functionality.

Finally, I apply some corrections to the core of `get_model_relations` to recognize deterministic node's parents and ended applying the same visualization (dashed) to the rendered graph as Numpyro. 

That`s it. Hope it works, or at least, it do the job on my project :nerd_face: 

About the merge intention, I just take the render-deterministic branch to continue the work done. It cannot be merged into the `dev` branch, can it? Or can it?

**Comment by r3v1** [comment]
Hi, any advances on this?

**Comment by eb8680** [comment]
@r3v1 could you revert your changes to the body of `pyro.deterministic` and refactor your new handler methods for `deterministic` to fit within handler methods for `sample`? Changing the `type` of `deterministic` will break some things elsewhere in Pyro and downstream.

You can just use a helper function to check within a `_pyro_sample`/`_pyro_post_sample` if a `sample` site came from `deterministic`:
```python
def site_is_deterministic(msg: dict) -> bool:
    return msg["type"] == "sample" and msg["infer"].get("_deterministic", False)

...

class ...:
    ...
    def _pyro_sample(self, msg):
        if site_is_deterministic(msg):
            # new logic for handling deterministic sites here
            ...
            return

        # old logic for handling sample sites here
        ...
```

**Comment by eb8680** [comment]
@r3v1 I also just changed the base branch to `dev`, can you resolve the merge conflicts and push so that CI can run tests?

**Pull request closed without merging**
