### PR TITLE
CVAE tutorial small improvement

### PR DESCRIPTION
**Pull request by ucals**
Hey guys,
Sorry to reopen this PR. Before moving to create another tutorial (next one will be the trajectory prediction paper), yesterday I had an idea to a visualization, which I think is pretty neat: check it out!

I added a video showing how the loss progresses throughout the training, and how the CVAE predictions evolve over time, going from blurry to clarity. I think it's cool, fun to watch :)

Unfortunately it cannot be seen directly in the .ipynb file, you have to run `make tutorial` to see it. Conversely, you can see in [this page](https://ucals.github.io/paper/2020/09/18/conditional-variational-auto-encoder.html#training), it renders exactly like that. Hope you dig it!

Cheers!

### CODE REVIEW

**Comment by eb8680** [comment]
Thanks for the update! Can you try rebasing your changes onto `dev` in a new branch so that the diff is shown correctly?

**Comment by ucals** [comment]
> Thanks for the update! Can you try rebasing your changes onto `dev` in a new branch so that the diff is shown correctly?

Done! Thanks!

**Comment by eb8680** [comment]
Looks like it's still incorrect. Can you open a new PR with a different branch (i.e. not `cvae_tutorial`) containing your changes to the tutorial?

**Comment by ucals** [comment]
> Thanks for the update! Can you try rebasing your changes onto `dev` in a new branch so that the diff is shown correctly?

Sorry, my bad.. I'm closing this PR and opening a new one...

**Pull request closed without merging**
