### PR TITLE
Concatenate torch docstrings at end of distribution wrappers

### PR DESCRIPTION
**Pull request by fritzo**
Fixes #3243 

This builds on @rtviii's PR and fixes errors:
- skips torch.py in doctest
- does some string munging to fix indentation
- removes pytorch xdoctest cruft
- fixes forecaster docstring error

@rtviii feel free to merge this into your branch, or we can merge this PR directly, either is fine 🙂 Thanks for contributing!

## For reviewers

[Before this PR](https://docs.pyro.ai/en/1.8.4/distributions.html#pytorch-distributions)
image

[After this PR](https://fritzo.org/temp/pyro/html/distributions.html#pytorch-distributions)
image

### CODE REVIEW

**Comment by rtviii** [comment]
Thank you for the awesome package.

**Review by martinjankowiak — APPROVED** [review]
lgtm do you have a link to a rendered version of this?

**Comment by fritzo** [comment]
@martinjankowiak I've added docs links and screenshots to the PR description.

**Comment by martinjankowiak** [comment]
@fritzo awesome should i go ahead and merge?

**Comment by fritzo** [comment]
Yes, @martinjankowiak could you please merge and I'll continue working towards the 1.8.6 release?

**Pull request merged**
