### PR TITLE
Tutorial on Bayesian workflow, with a SARS-CoV-2 running example

### PR DESCRIPTION
**Pull request by fritzo**
[open in colab](https://colab.research.google.com/github/pyro-ppl/pyro/blob/workflow-tutorial/tutorial/source/workflow.ipynb)

This also adds the helper utility
- `pyro.ops.special.sparse_multinomial_likelihood`

### CODE REVIEW

**Comment by martinjankowiak** [comment]
comments:
- typo: intellitently
- toc entry six missing closing ); alternatively change to colon
- MCMC is mentioned in overview but not elsewhere. remove?
- nit: "PANGO lineages of samples" +genomic
- "should lead to an approximately block diagonal covariance matrix" this is ambiguous. you mean "... in the approximate posterior... when using a mvn variational distribution" or something
- "While in principle you could be Bayesian about everything, it's best to focus probabilistic inference on the truly uncertain parts of your problem." out of context, remove?
- `5.5 / dataset["time_step_days"]` should be inverted
- more comments/description of model? or explicitly defer/link to intro logistic growth tutorial?
- explain `0.01`?
- nit: "is implausibly narrow" => "may be"
- "...is less sensitive to reparametrization." maybe +"w.r.t. interpreting the results of inference or something?" optimization performance is affected in both cases
- more text to make the way you move between log/exp space more clear? "most mutations have very little effect"
- typo: initialzing
- typo: wavely
- nit: `HaarReparam` +"(where appropriate)"?
- "Try combining multiple guides" => +"using"
- some sort of concluding sentence?

**Comment by fritzo** [comment]
Thanks for the detailed review @martinjankowiak, I've tried to address all your review comments.

**Comment by martinjankowiak** [comment]
looks great!
- typo: its's
- typo: multiplicitave
- missing word: we'll need duplicate
- typo: space,,
- typo: langauges
- typo: initialzation

**Comment by fritzo** [comment]
done

**Review by martinjankowiak — APPROVED** [review]

**Pull request merged**
